name: Build C++ Project

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download zasm source
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/m417z/zasm/archive/refs/heads/main.zip" -OutFile "zasm.zip"
        Expand-Archive -Path "zasm.zip" -DestinationPath "."
        Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "zasm"
        Rename-Item -Path "zasm-main" -NewName "zasm"

    - name: Configure CMake
      run: cmake -B build -S . -A x64

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: themida-deobf-exe
        path: |
          build/**/*.exe
