name: Build C++ Project

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout zasm manually if missing
      run: |
        if not exist "zasm\include" (
          git clone https://github.com/m417z/zasm.git zasm
        )
      shell: cmd

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild ThemidaProject/ThemidaProject.vcxproj /p:Configuration=Release /p:Platform=x64 /p:IncludePath="zasm\include;ThemidaProject"
      shell: cmd
